server:
  port: 8081
  shutdown: graceful
service:
  environment: local
spring:
  application:
    name: libri-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    write:
      username: libri_user
      password: libri_password
      url: jdbc:mysql://localhost:3306/libri_db?useUnicode=yes&useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=utf8&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull&sendFractionalSeconds=false
    read:
      username: libri_user
      password: libri_password
      url: jdbc:mysql://localhost:3306/libri_db?useUnicode=yes&useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=utf8&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull&sendFractionalSeconds=false
  jackson:
    time-zone: Asia/Seoul
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        default_batch_fetch_size: 1000
        query:
          plan_cache_max_size: 500
          plan_parameter_metadata_max_size: 32
        envers:
          store_data_at_delete: true
  h2:
    console:
      enabled: false
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  lifecycle:
    timeout-per-shutdown-phase: 20s #default 30s
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: profile, email
            redirect-uri: "http://localhost:8080/login/oauth2/code/google"

jwt:
  secret: a7d8f6g5h4j3k2l1m0n9p8o7q6r5s4t3u2v1w0x9y8z7a6b5c4d3e2f1g0h
  expiration: 3600000
  refresh-expiration: 604800000

feign:
  client:app:
    config:
      default:
        loggerLevel: full

app:
  cors:
    allowedOrigins: http://localhost:8080, localhost:8081, http://localhost:3000

logging:
  level:
    org.hibernate:
      type: debug
    org.springframework.web.client: trace

management:
  endpoints:
    web:
      exposure:
        include: health