services:
  mysql:
    platform: linux/x86_64
    image: mysql:8.0.23
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    container_name: mysql
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --character_set_filesystem=binary
      - --skip-character-set-client-handshake
      - --sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=libri
      - MYSQL_ROOT_PASSWORD=1234
      - TZ=Asia/Seoul
    volumes:
      - ./mysql:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d