package com.swyp.libri.global.error.exception;

public enum ErrorCode {
    /*
        공통 에러
    */

	ERR_INTERNAL_SERVER_ERROR("ERR_INTERNAL_SERVER_ERROR"),

	ERR_INVALID_INPUT_VALUE("ERR_INVALID_INPUT_VALUE"),

	ERR_METHOD_NOT_ALLOWED("ERR_METHOD_NOT_ALLOWED"),

	ERR_ENTITY_NOT_FOUND("ERR_ENTITY_NOT_FOUND"),

	ERR_ENTITY_DUPLICATE("ERR_ENTITY_DUPLICATE"),

	ERR_ENTITY_NOT_MATCHED("ERR_ENTITY_NOT_MATCHED"),

	ERR_INVALID_TYPE_VALUE("ERR_INVALID_TYPE_VALUE"),

	ERR_HANDLE_ACCESS_DENIED("ERR_HANDLE_ACCESS_DENIED"),

	ERR_BUSINESS("ERR_BUSINESS"),

	ERR_UNAUTHORIZED("ERR_UNAUTHORIZED"),

	ERR_DB_INSERT("ERR_DB_INSERT"),

	ERR_JSON_PROCESSING("ERR_JSON_PROCESSING"),


	ERR_INVALID_EMAIL_VALUE("ERR_INVALID_EMAIL_VALUE"),
	ERR_TOO_MANY_REQUEST_ERROR("ERR_TOO_MANY_REQUEST_ERROR"),



	/*
		Feign 통신 에러
	 */
	ERR_FEIGN_CLIENT("ERR_FEIGN_CLIENT"),

	/*
		AWS SERVICE ERROR
	 */
	ERR_AWS_SERVICE("ERR_AWS_SERVICE")

;

	private final String value;

	ErrorCode(String value) {
		this.value = value;
	}

	public String getValue() {
		return value;
	}
}
